sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aleksiuu/Dockerized-react.ci -f Dockerfile.dev .

script:
  - docker run -e CI=true aleksiuu/Dockerized-react-ci npm run test
