sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t <container-name> -f Dockerfile.dev .

script:
  - docker run -e CI=true <container-name> npm run test

deploy:
  provider: elasticbeanstalk
  region: "<AWS Region>"
  app: "<Elastic Beanstalk App name>"
  env: "<Elastic Beanstalk Environment name>"
  bucket_name: "Elastic Beanstalk S3-bucket name"
  bucket_path: "<S3 bucket path for example: docker-react>"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY